version: '3'

services:
  server:
    build: './'
    container_name: 'Event-Booking-App'
    depends_on:
      - 'db'
    links:
      - 'db'
    ports:
      - '3000:3000'
    volumes:
      - './:/usr/src/app'
    command: 'npm start'

  db:
    image: 'mongo'
    ports:
      - '27017:27017'
